name: Test and deploy
on:
  push:
    branches:
      - actions

jobs:
  lint:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - run: yarn install
      - run: yarn lint

  deploy-dev:
    if: github.ref == 'refs/heads/actions'
    needs: lint
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - run: yarn install
      - run: yarn deploy:dev

  deploy-prod:
    if: github.ref == 'refs/heads/master'
    needs: lint
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - run: echo "foo"
